CREATE TABLE `PYP_PROGRAMA` (
  `ID_PYP` int(11) NOT NULL AUTO_INCREMENT,
  `COD_PROG_PYP` varchar(255) DEFAULT NULL,
  `NOM_PROG_PYP` varchar(255) DEFAULT NULL,
  `ACTIVO` tinyint(1) DEFAULT NULL,
  `EDAD_INICIAL` int(11) DEFAULT NULL,
  `U_EDAD_INICIAL` int(11) DEFAULT NULL,
  `EDAD_FINAL` int(11) DEFAULT NULL,
  `U_EDAD_FINAL` int(11) DEFAULT NULL,
  `GENERO` int(11) DEFAULT NULL,
  `ZONA` int(11) DEFAULT NULL,
  `GESTANTE` tinyint(1) DEFAULT '0',
  `IS_ACTIVE` tinyint(1) DEFAULT '1',
  `FEC_CREACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_PYP`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

CREATE TABLE `PYP_PROG_CONTRATO` (
  `ID_PYP_CONTRATO` int(11) NOT NULL,
  `ID_PYP` int(11) DEFAULT NULL,
  `ID_CONTRATO` int(11) DEFAULT NULL,
  `META_MENSUAL` int(11) DEFAULT NULL,
  `ACTIVO` tinyint(1) DEFAULT '1',
  `FEC_CREACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_PYP_CONTRATO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PYP_PROG_ITEM` (
  `ID_PYP_PROG_ITEM` int(11) NOT NULL AUTO_INCREMENT,
  `ID_ITEM` int(11) DEFAULT NULL,
  `CANTIDAD` int(11) DEFAULT NULL,
  `FRECUENCIA` int(11) DEFAULT NULL,
  `UNIDAD_FRECUENCIA` int(11) DEFAULT NULL,
  `ID_USUARIO` int(11) DEFAULT NULL,
  `FEC_CREACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_PYP_PROG_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

